# Basic concepts of quasispecies simulation

```{r, include=FALSE}
library(yasss)
library(knitr)
library(formattable)
knitr::opts_chunk$set(echo = FALSE)
```

```{r , include = FALSE}
sim_pop_arg_formatter <- function(args){
  arg_table <- data.frame(arg = character(0),
                          val = character(0),
                          stringsAsFactors = FALSE)
  arg_table <- do.call(rbind, list(
data.frame(arg = "Number of Ancestors", val = length(args$ancestors)),
data.frame(arg = "Sequence Length",     val = paste(nchar(args$ancestors), collapse = ', ')),
data.frame(arg = "r0",                  val = args$r0),
data.frame(arg = "Number of Generations", val = args$n_gen),
data.frame(arg = "Minimum Population Size", val = args$n_pop),
data.frame(arg = "Mutator Function", val = args$mutator$fun),
data.frame(arg = paste("Mutator: ", names(args$mutator$args), sep = ''),
           val = unlist(args$mutator$args)),
data.frame(arg = "Fitness Evaluator", val = args$fitness_evaluator$fun)
))

  if (is.null(args$fitness_evaluator$args)){
    arg_table <- rbind(arg_table,
      data.frame(arg = "Additional Fitness Evaluator Arguments",
                 val = "None")
      )
  } else {
    arg_table <- rbind(arg_table,
      data.frame(arg = paste("Fitness Evaluator: ", names(args$fitness_evaluator$args), sep = ''),
                 val = unlist(args$fitness_evaluator$args))
    )
  }
  row.names(arg_table) <- NULL
  names(arg_table) <- c("Argument", "Value")
  return(arg_table)
}

genealogy_summary_table <- function(genealogy){
  genealogy$ances_dist <- stringdist(genealogy[1,'the_seq'], genealogy[,'the_seq'])
  genealogy_summary <-
  genealogy %>% 
  select(gen_num, ances_dist, the_seq, fitness_score) %>% 
  group_by(gen_num) %>%
  summarize(n = n(),
            ances_dist = mean(ances_dist),
            nor_ances_dist = mean(ances_dist) / min(nchar(the_seq)),
            fitness_score = mean(fitness_score),
            min_fitness_score = min(fitness_score))
  names(genealogy_summary) <- c(
    "Gen. Num.",
    "n",
    "Dist. to Ances.",
    "Normalized Dist.",
    "Fitness Score",
    "Min. Fitness Score"
  )
  return(genealogy_summary)
}

style_def <- function(x){
  style(display = "inline-block",
        direction = "rtl",
        `border-radius` = "4px", 
        `padding-right` = "15px", 
        `padding-left` = "15px", 
        `background-color` = csscolor("white")
        )
}

style_lister <- function(df){
  style_list <- list()
  for (i in names(df)){
    style_list[[i]] <- formatter(.tag = "span", style = style_def)
  }
  return(style_list)
}
```

## Simple first simulation

```{r, results = 'asis'}
args <- list(
  ancestors = paste(rep("A", 500), collapse = ''),
  r0 = 2,
  n_gen = 9,
  n_pop = Inf,
  mutator = list(fun = "mutator_uniform_fun",
                 args = list(mu = 0.1)),
  fitness_evaluator = list(fun = "fitness_evaluator_uniform_fun",
                           args = NULL)
)

x <- do.call(sim_pop, args)

cat("\n\nTable: Called sim_pop with the following arguments.\n\n")
format_table(sim_pop_arg_formatter(args), format = "html")

g_sum_tab <- genealogy_summary_table(x)

cat("\n\nTable: Individuals per generation and the average distance to the original ancestor for the generation.\n\n")
format_table(g_sum_tab, format = 'html')

cat("\n\nTable: Individuals per generation and the average distance to the original ancestor for the generation.\n\n")
format_table(g_sum_tab, style_lister(g_sum_tab), align = 'c')
```

### Looking at only the last generation now

```{r, include = FALSE}
last_gen <-
x %>%
  filter(gen_num == max(gen_num))

dmat <- stringdistmatrix(last_gen$the_seq, method = 'hamming')
avg_hd <- mean(dmat)
dvec <- as.numeric(dmat)/min(nchar(last_gen$the_seq))
dd.f <- data.frame(dists = dvec)
```

The average pairwise HD is `r round(avg_hd, 2)` and normalized by the length of the sequence it is `r round(avg_hd/min(nchar(last_gen$the_seq)), 3)`.

```{r, results = 'asis'}
ggplot(dd.f, aes(x = dists)) + geom_density()
cat("\n\nFigure: Density plot of the pariwise distances in the last generation.\n\n")

deciles <-
data.frame(Decile = paste((0:10)*10, "%", sep = ''),
           Value = quantile(dvec, (0:10)/10))
row.names(deciles) <- NULL
cat("\n\nTable: The Deciles of the pairwise HDs.\n\n")
format_table(deciles, list(
  Decile = formatter(.tag = "span",
    style = style_def
    ),
  Value = formatter(.tag = "span",
    style = style_def
    )
  ),
  align = 'c'
)
```
