The following tables show some summary metrics for `r length(unique(all_sim_results$sim_id))` simulations.

```{r, include = FALSE}
seq_length <- nchar(all_sim_results[1,'the_seq'])

last_gens <-
all_sim_results %>%
  filter(gen_num == max(gen_num))

dd.f <- NULL
for (i in unique(all_sim_results$sim_id)){
  dmat <- stringdistmatrix(last_gens$the_seq[last_gens$sim_id == i], method = 'hamming')
  avg_hd <- mean(dmat)
  dvec <- as.numeric(dmat)/min(nchar(last_gen$the_seq))
  dd.f <- rbind(dd.f,
    data.frame(sim_id = i,
               dists = dvec)
  )
}

kable(
  dd.f %>%
    group_by(sim_id) %>%
    summarize(avg_hd = round(mean(dists),4),
              n_avg_hd = round(mean(dists)/seq_length, 7)),
  booktabs = TRUE,
  caption = "The average pairwise HD for each simulation"
)
```

```{r, fig.cap='Density plot of the pariwise distances in the last generation', results = 'asis'}
n_uniq <- length(unique(dd.f$dists))
range_length <- max(dd.f$dists) - min(dd.f$dists)
bw <- range_length / min((n_uniq*1.75), 200)
ggplot(dd.f, aes(x = dists, 
                 col = as.factor(sim_id))) + 
      geom_density(bw = bw)
```

```{r, results = 'asis'}
all_deciles <- data.frame(matrix(0, ncol = 12, nrow = max(all_sim_results$sim_id)))
names(all_deciles) <- c('Sim', paste((0:10)*10, "%", sep = ''))

for (i in 1:max(all_sim_results$sim_id)){
  deciles <-
    quantile(dd.f$dists[dd.f$sim_id == i], (0:10)/10)

  all_deciles[i,] <- c(i, deciles)
}
row.names(all_deciles) <- NULL

kable(
  all_deciles,
  booktabs = TRUE,
  caption = "The deciles of the pairwise HDs"
)
```

```{r, results = 'asis'}
kable(
  sim_pop_arg_formatter(sim_result$args),
  booktabs = TRUE,
  caption = "Configuration with which sim_pop was called."
)
```

```{r, results = 'asis'}
g_sum_tab <- genealogy_summary_table(all_sim_results[all_sim_results$sim_id == 1, -1])

kable(
  g_sum_tab,
  booktabs = TRUE,
  caption = "Individuals per generation and the average distance to the original ancestor for the generation in the first simulation only."
)
```

